AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template zum Erstellen einer EC2-Instanz (t2.micro)

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e9527f5ffe6b54fd                                 # <-- WIRD AUTOMATISCH VOM PARAMETER GESETZT
      SecurityGroupIds:
        - sg-05dffbeeaa0e71888                           # <-- WIRD AUTOMATISCH VOM PARAMETER GESETZT
